// Catalogue de mouvements pour l'analyseur WOD
// Chaque mouvement définit sa dominante / secondaires / filière / charge typique

export type Energetics = "atp_pcr" | "glycolytic" | "oxidative";

export type Capacity =
  | "force_max"
  | "puissance"
  | "endurance_force"
  | "vo2max"
  | "lactique"
  | "gainage"
  | "skill";

export type Category =
  | "weightlifting"
  | "gymnastics"
  | "cardio"
  | "hyrox"
  | "core";

export interface MovementDef {
  id: string;
  name: string; // canonical FR/EN display
  aliases: RegExp[]; // patterns regex à matcher (text minuscule)
  category: Category;
  dominantCapacity: Capacity;
  secondaryCapacities: Capacity[];
  energetics: { atp_pcr: number; glycolytic: number; oxidative: number }; // sommes à ~1
  // Charge typique relative au 1RM (0 = poids du corps, 1 = max). Utilisé pour bonus Force max.
  typicalLoad: number;
  // Temps moyen par rep (secondes) — pour estimer la durée d'un For Time
  secondsPerRep: number;
  // Détectable comme un mouvement cardio monostructurel (distance)?
  isCardio?: boolean;
}

// helper to build aliases (case-insensitive whole word matching done by parser)
// Pluriels acceptés automatiquement: \b<pattern>(?:s|es)?\b
const re = (...arr: string[]): RegExp[] =>
  arr.map((p) => new RegExp(`\\b${p}(?:s|es)?\\b`, "i"));

export const MOVEMENTS: MovementDef[] = [
  // ─── HALTEROPHILIE / FORCE ────────────────────────────────────────────────
  {
    id: "back_squat",
    name: "Back Squat",
    aliases: re("back\\s*squat", "squat\\s*arriere", "back-squat"),
    category: "weightlifting",
    dominantCapacity: "force_max",
    secondaryCapacities: ["gainage", "puissance"],
    energetics: { atp_pcr: 0.85, glycolytic: 0.15, oxidative: 0 },
    typicalLoad: 0.85,
    secondsPerRep: 6,
  },
  {
    id: "front_squat",
    name: "Front Squat",
    aliases: re("front\\s*squat", "squat\\s*avant"),
    category: "weightlifting",
    dominantCapacity: "force_max",
    secondaryCapacities: ["gainage", "skill"],
    energetics: { atp_pcr: 0.8, glycolytic: 0.2, oxidative: 0 },
    typicalLoad: 0.75,
    secondsPerRep: 5,
  },
  {
    id: "overhead_squat",
    name: "Overhead Squat",
    aliases: re("overhead\\s*squat", "ohs", "squat\\s*overhead"),
    category: "weightlifting",
    dominantCapacity: "skill",
    secondaryCapacities: ["gainage", "force_max"],
    energetics: { atp_pcr: 0.75, glycolytic: 0.25, oxidative: 0 },
    typicalLoad: 0.55,
    secondsPerRep: 5,
  },
  {
    id: "deadlift",
    name: "Deadlift",
    aliases: re("deadlift", "soulev[ée]\\s*de\\s*terre", "dl"),
    category: "weightlifting",
    dominantCapacity: "force_max",
    secondaryCapacities: ["gainage", "endurance_force"],
    energetics: { atp_pcr: 0.85, glycolytic: 0.15, oxidative: 0 },
    typicalLoad: 0.85,
    secondsPerRep: 5,
  },
  {
    id: "sumo_dl",
    name: "Sumo Deadlift High Pull",
    aliases: re("sdhp", "sumo\\s*deadlift\\s*high\\s*pull", "sumo\\s*deadlift"),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["endurance_force", "gainage"],
    energetics: { atp_pcr: 0.55, glycolytic: 0.4, oxidative: 0.05 },
    typicalLoad: 0.5,
    secondsPerRep: 3,
  },
  {
    id: "power_clean",
    name: "Power Clean",
    aliases: re("power\\s*clean", "epaul[ée](-jet[ée])?\\s*force"),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["force_max", "skill"],
    energetics: { atp_pcr: 0.85, glycolytic: 0.15, oxidative: 0 },
    typicalLoad: 0.7,
    secondsPerRep: 4,
  },
  {
    id: "squat_clean",
    name: "Squat Clean",
    aliases: re("squat\\s*clean", "epaul[ée]\\s*flexion"),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["force_max", "skill"],
    energetics: { atp_pcr: 0.8, glycolytic: 0.2, oxidative: 0 },
    typicalLoad: 0.75,
    secondsPerRep: 5,
  },
  {
    id: "clean_jerk",
    name: "Clean & Jerk",
    aliases: re(
      "clean\\s*(and|&|et)\\s*jerk",
      "c&j",
      "c\\s*\\+\\s*j",
      "epaul[ée]-jet[ée]",
      "epaul[ée]\\s*jet[ée]"
    ),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["force_max", "skill"],
    energetics: { atp_pcr: 0.85, glycolytic: 0.15, oxidative: 0 },
    typicalLoad: 0.75,
    secondsPerRep: 5,
  },
  {
    id: "power_snatch",
    name: "Power Snatch",
    aliases: re("power\\s*snatch", "arrach[ée]\\s*force"),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["skill", "force_max"],
    energetics: { atp_pcr: 0.85, glycolytic: 0.15, oxidative: 0 },
    typicalLoad: 0.6,
    secondsPerRep: 4,
  },
  {
    id: "squat_snatch",
    name: "Squat Snatch",
    aliases: re("squat\\s*snatch", "arrach[ée]\\s*flexion", "(?<!power\\s)snatch"),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["skill", "force_max"],
    energetics: { atp_pcr: 0.85, glycolytic: 0.15, oxidative: 0 },
    typicalLoad: 0.65,
    secondsPerRep: 5,
  },
  {
    id: "push_press",
    name: "Push Press",
    aliases: re("push\\s*press"),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["force_max", "gainage"],
    energetics: { atp_pcr: 0.75, glycolytic: 0.25, oxidative: 0 },
    typicalLoad: 0.65,
    secondsPerRep: 3,
  },
  {
    id: "push_jerk",
    name: "Push Jerk",
    aliases: re("push\\s*jerk"),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["force_max", "skill"],
    energetics: { atp_pcr: 0.85, glycolytic: 0.15, oxidative: 0 },
    typicalLoad: 0.7,
    secondsPerRep: 3,
  },
  {
    id: "split_jerk",
    name: "Split Jerk",
    aliases: re("split\\s*jerk"),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["force_max", "skill"],
    energetics: { atp_pcr: 0.9, glycolytic: 0.1, oxidative: 0 },
    typicalLoad: 0.8,
    secondsPerRep: 4,
  },
  {
    id: "strict_press",
    name: "Strict Press",
    aliases: re("strict\\s*press", "shoulder\\s*press", "overhead\\s*press"),
    category: "weightlifting",
    dominantCapacity: "force_max",
    secondaryCapacities: ["gainage"],
    energetics: { atp_pcr: 0.85, glycolytic: 0.15, oxidative: 0 },
    typicalLoad: 0.7,
    secondsPerRep: 4,
  },
  {
    id: "bench_press",
    name: "Bench Press",
    aliases: re("bench\\s*press", "developp[ée]\\s*couch[ée]"),
    category: "weightlifting",
    dominantCapacity: "force_max",
    secondaryCapacities: ["puissance"],
    energetics: { atp_pcr: 0.9, glycolytic: 0.1, oxidative: 0 },
    typicalLoad: 0.8,
    secondsPerRep: 4,
  },
  {
    id: "thruster",
    name: "Thruster",
    aliases: re("thruster"),
    category: "weightlifting",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["puissance", "vo2max", "gainage"],
    energetics: { atp_pcr: 0.2, glycolytic: 0.65, oxidative: 0.15 },
    typicalLoad: 0.55,
    secondsPerRep: 3,
  },
  {
    id: "wall_ball",
    name: "Wall Ball",
    aliases: re("wall\\s*ball(s)?", "wb"),
    category: "weightlifting",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["vo2max", "puissance"],
    energetics: { atp_pcr: 0.1, glycolytic: 0.55, oxidative: 0.35 },
    typicalLoad: 0.3,
    secondsPerRep: 2.5,
  },
  {
    id: "kb_swing",
    name: "Kettlebell Swing",
    aliases: re(
      "kb\\s*swing",
      "kettlebell\\s*swing",
      "american\\s*swing",
      "russian\\s*swing",
      "swing\\s*kb"
    ),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["endurance_force", "gainage"],
    energetics: { atp_pcr: 0.25, glycolytic: 0.55, oxidative: 0.2 },
    typicalLoad: 0.35,
    secondsPerRep: 2,
  },
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    aliases: re("goblet\\s*squat"),
    category: "weightlifting",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["gainage"],
    energetics: { atp_pcr: 0.3, glycolytic: 0.5, oxidative: 0.2 },
    typicalLoad: 0.4,
    secondsPerRep: 3,
  },
  {
    id: "tgu",
    name: "Turkish Get-Up",
    aliases: re("turkish\\s*get(-|\\s*)up", "tgu"),
    category: "weightlifting",
    dominantCapacity: "gainage",
    secondaryCapacities: ["skill", "force_max"],
    energetics: { atp_pcr: 0.4, glycolytic: 0.3, oxidative: 0.3 },
    typicalLoad: 0.4,
    secondsPerRep: 25,
  },
  {
    id: "devil_press",
    name: "Devil Press",
    aliases: re("devil\\s*press"),
    category: "weightlifting",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["puissance", "vo2max"],
    energetics: { atp_pcr: 0.2, glycolytic: 0.55, oxidative: 0.25 },
    typicalLoad: 0.45,
    secondsPerRep: 6,
  },
  {
    id: "db_snatch",
    name: "Dumbbell Snatch",
    aliases: re("(db|dumbbell|haltere)\\s*snatch", "dumbbell\\s*snatch"),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["endurance_force", "skill"],
    energetics: { atp_pcr: 0.4, glycolytic: 0.5, oxidative: 0.1 },
    typicalLoad: 0.4,
    secondsPerRep: 2.5,
  },
  {
    id: "db_clean",
    name: "Dumbbell Clean",
    aliases: re("(db|dumbbell)\\s*clean"),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["endurance_force"],
    energetics: { atp_pcr: 0.4, glycolytic: 0.5, oxidative: 0.1 },
    typicalLoad: 0.4,
    secondsPerRep: 3,
  },

  // ─── GYMNASTIQUE ──────────────────────────────────────────────────────────
  {
    id: "pullup",
    name: "Pull-Up",
    aliases: re(
      "pull[-\\s]?up(s)?",
      "tractions?",
      "kipping\\s*pull",
      "butterfly\\s*pull",
      "strict\\s*pull"
    ),
    category: "gymnastics",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["puissance", "skill"],
    energetics: { atp_pcr: 0.25, glycolytic: 0.55, oxidative: 0.2 },
    typicalLoad: 0.6,
    secondsPerRep: 2,
  },
  {
    id: "c2b",
    name: "Chest-to-Bar",
    aliases: re("c2b", "chest[-\\s]?to[-\\s]?bar"),
    category: "gymnastics",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["skill", "puissance"],
    energetics: { atp_pcr: 0.3, glycolytic: 0.55, oxidative: 0.15 },
    typicalLoad: 0.65,
    secondsPerRep: 2.5,
  },
  {
    id: "bar_mu",
    name: "Bar Muscle-Up",
    aliases: re("bar\\s*muscle[-\\s]?up", "bmu"),
    category: "gymnastics",
    dominantCapacity: "skill",
    secondaryCapacities: ["puissance", "force_max"],
    energetics: { atp_pcr: 0.6, glycolytic: 0.35, oxidative: 0.05 },
    typicalLoad: 0.75,
    secondsPerRep: 5,
  },
  {
    id: "ring_mu",
    name: "Ring Muscle-Up",
    aliases: re("ring\\s*muscle[-\\s]?up", "rmu", "muscle[-\\s]?up"),
    category: "gymnastics",
    dominantCapacity: "skill",
    secondaryCapacities: ["force_max", "puissance"],
    energetics: { atp_pcr: 0.7, glycolytic: 0.3, oxidative: 0 },
    typicalLoad: 0.8,
    secondsPerRep: 6,
  },
  {
    id: "pushup",
    name: "Push-Up",
    aliases: re(
      "push[-\\s]?up(s)?",
      "pompes?",
      "hand\\s*release\\s*push",
      "hrpu"
    ),
    category: "gymnastics",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["gainage"],
    energetics: { atp_pcr: 0.15, glycolytic: 0.5, oxidative: 0.35 },
    typicalLoad: 0.4,
    secondsPerRep: 1.5,
  },
  {
    id: "hspu",
    name: "Handstand Push-Up",
    aliases: re("hspu", "handstand\\s*push[-\\s]?up"),
    category: "gymnastics",
    dominantCapacity: "skill",
    secondaryCapacities: ["force_max", "gainage"],
    energetics: { atp_pcr: 0.5, glycolytic: 0.45, oxidative: 0.05 },
    typicalLoad: 0.7,
    secondsPerRep: 3,
  },
  {
    id: "hs_walk",
    name: "Handstand Walk",
    aliases: re("handstand\\s*walk", "hs\\s*walk"),
    category: "gymnastics",
    dominantCapacity: "skill",
    secondaryCapacities: ["gainage", "endurance_force"],
    energetics: { atp_pcr: 0.4, glycolytic: 0.4, oxidative: 0.2 },
    typicalLoad: 0.5,
    secondsPerRep: 30, // par 25 ft / 7.5m
  },
  {
    id: "t2b",
    name: "Toes-to-Bar",
    aliases: re("t2b", "toes[-\\s]?to[-\\s]?bar"),
    category: "gymnastics",
    dominantCapacity: "gainage",
    secondaryCapacities: ["endurance_force", "skill"],
    energetics: { atp_pcr: 0.3, glycolytic: 0.5, oxidative: 0.2 },
    typicalLoad: 0.5,
    secondsPerRep: 2,
  },
  {
    id: "k2e",
    name: "Knees-to-Elbow",
    aliases: re("k2e", "knees[-\\s]?to[-\\s]?elbow"),
    category: "gymnastics",
    dominantCapacity: "gainage",
    secondaryCapacities: ["endurance_force"],
    energetics: { atp_pcr: 0.2, glycolytic: 0.5, oxidative: 0.3 },
    typicalLoad: 0.45,
    secondsPerRep: 2,
  },
  {
    id: "situp",
    name: "Sit-Up",
    aliases: re("sit[-\\s]?up(s)?", "abdos"),
    category: "core",
    dominantCapacity: "gainage",
    secondaryCapacities: ["endurance_force"],
    energetics: { atp_pcr: 0.1, glycolytic: 0.4, oxidative: 0.5 },
    typicalLoad: 0.2,
    secondsPerRep: 2,
  },
  {
    id: "ghd",
    name: "GHD Sit-Up",
    aliases: re("ghd\\s*sit[-\\s]?up", "ghd"),
    category: "core",
    dominantCapacity: "gainage",
    secondaryCapacities: ["endurance_force"],
    energetics: { atp_pcr: 0.15, glycolytic: 0.45, oxidative: 0.4 },
    typicalLoad: 0.3,
    secondsPerRep: 2.5,
  },
  {
    id: "plank",
    name: "Plank",
    aliases: re("plank", "gainage"),
    category: "core",
    dominantCapacity: "gainage",
    secondaryCapacities: ["endurance_force"],
    energetics: { atp_pcr: 0.1, glycolytic: 0.3, oxidative: 0.6 },
    typicalLoad: 0.3,
    secondsPerRep: 60,
  },
  {
    id: "hollow",
    name: "Hollow Hold",
    aliases: re("hollow\\s*hold", "hollow"),
    category: "core",
    dominantCapacity: "gainage",
    secondaryCapacities: [],
    energetics: { atp_pcr: 0.15, glycolytic: 0.35, oxidative: 0.5 },
    typicalLoad: 0.3,
    secondsPerRep: 30,
  },
  {
    id: "lsit",
    name: "L-Sit",
    aliases: re("l[-\\s]?sit"),
    category: "core",
    dominantCapacity: "gainage",
    secondaryCapacities: ["skill", "force_max"],
    energetics: { atp_pcr: 0.4, glycolytic: 0.4, oxidative: 0.2 },
    typicalLoad: 0.4,
    secondsPerRep: 20,
  },
  {
    id: "pistol",
    name: "Pistol Squat",
    aliases: re("pistol(s)?", "single\\s*leg\\s*squat"),
    category: "gymnastics",
    dominantCapacity: "skill",
    secondaryCapacities: ["gainage", "force_max"],
    energetics: { atp_pcr: 0.35, glycolytic: 0.45, oxidative: 0.2 },
    typicalLoad: 0.5,
    secondsPerRep: 3,
  },
  {
    id: "box_jump",
    name: "Box Jump",
    aliases: re("box\\s*jump(s)?", "saut[s]?\\s*sur\\s*box"),
    category: "gymnastics",
    dominantCapacity: "puissance",
    secondaryCapacities: ["vo2max", "endurance_force"],
    energetics: { atp_pcr: 0.45, glycolytic: 0.35, oxidative: 0.2 },
    typicalLoad: 0.3,
    secondsPerRep: 3,
  },
  {
    id: "box_step",
    name: "Box Step-Up",
    aliases: re("box\\s*step[-\\s]?up(s)?", "step[-\\s]?up(s)?"),
    category: "gymnastics",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["vo2max"],
    energetics: { atp_pcr: 0.1, glycolytic: 0.3, oxidative: 0.6 },
    typicalLoad: 0.3,
    secondsPerRep: 3,
  },
  {
    id: "burpee",
    name: "Burpee",
    aliases: re("burpee(s)?(?!\\s*box)(?!\\s*broad)"),
    category: "gymnastics",
    dominantCapacity: "vo2max",
    secondaryCapacities: ["endurance_force", "gainage"],
    energetics: { atp_pcr: 0.1, glycolytic: 0.45, oxidative: 0.45 },
    typicalLoad: 0.3,
    secondsPerRep: 4,
  },
  {
    id: "burpee_box",
    name: "Burpee Box Jump-Over",
    aliases: re("burpee\\s*box\\s*jump[-\\s]?over", "burpee\\s*box\\s*jump"),
    category: "gymnastics",
    dominantCapacity: "vo2max",
    secondaryCapacities: ["puissance", "endurance_force"],
    energetics: { atp_pcr: 0.15, glycolytic: 0.45, oxidative: 0.4 },
    typicalLoad: 0.35,
    secondsPerRep: 5,
  },
  {
    id: "rope_climb",
    name: "Rope Climb",
    aliases: re("rope\\s*climb", "grimper\\s*de\\s*corde"),
    category: "gymnastics",
    dominantCapacity: "skill",
    secondaryCapacities: ["force_max", "endurance_force"],
    energetics: { atp_pcr: 0.45, glycolytic: 0.4, oxidative: 0.15 },
    typicalLoad: 0.65,
    secondsPerRep: 20,
  },
  {
    id: "du",
    name: "Double-Under",
    aliases: re("double[-\\s]?under(s)?", "du(s)?"),
    category: "gymnastics",
    dominantCapacity: "skill",
    secondaryCapacities: ["vo2max", "endurance_force"],
    energetics: { atp_pcr: 0.1, glycolytic: 0.3, oxidative: 0.6 },
    typicalLoad: 0.15,
    secondsPerRep: 0.6,
  },
  {
    id: "su",
    name: "Single-Under",
    aliases: re("single[-\\s]?under(s)?"),
    category: "gymnastics",
    dominantCapacity: "vo2max",
    secondaryCapacities: ["endurance_force"],
    energetics: { atp_pcr: 0.05, glycolytic: 0.2, oxidative: 0.75 },
    typicalLoad: 0.1,
    secondsPerRep: 0.5,
  },
  {
    id: "air_squat",
    name: "Air Squat",
    aliases: re("air\\s*squat(s)?", "squat(s)?\\s*sans\\s*charge"),
    category: "gymnastics",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["vo2max"],
    energetics: { atp_pcr: 0.05, glycolytic: 0.35, oxidative: 0.6 },
    typicalLoad: 0.15,
    secondsPerRep: 1.5,
  },
  {
    id: "lunge",
    name: "Lunge",
    aliases: re("lunge(s)?", "fente(s)?", "walking\\s*lunge"),
    category: "gymnastics",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["gainage"],
    energetics: { atp_pcr: 0.1, glycolytic: 0.4, oxidative: 0.5 },
    typicalLoad: 0.3,
    secondsPerRep: 2,
  },

  // ─── CARDIO MONOSTRUCTUREL ────────────────────────────────────────────────
  {
    id: "run",
    name: "Course",
    aliases: re("run", "course", "courir", "running", "mile"),
    category: "cardio",
    dominantCapacity: "vo2max",
    secondaryCapacities: ["endurance_force"],
    energetics: { atp_pcr: 0.02, glycolytic: 0.18, oxidative: 0.8 },
    typicalLoad: 0.1,
    secondsPerRep: 0.24, // ~4 min/km => 240s/1000m = 0.24s/m
    isCardio: true,
  },
  {
    id: "row",
    name: "Row (Rameur)",
    aliases: re("row(?!\\s*pull)", "rameur", "concept2", "c2\\s*row"),
    category: "cardio",
    dominantCapacity: "vo2max",
    secondaryCapacities: ["endurance_force", "lactique"],
    energetics: { atp_pcr: 0.05, glycolytic: 0.3, oxidative: 0.65 },
    typicalLoad: 0.2,
    secondsPerRep: 0.2, // ~3:20/500m => 200s/500m = 0.4 -> ajusté 0.2s/m
    isCardio: true,
  },
  {
    id: "echo_bike",
    name: "Echo Bike",
    aliases: re("echo\\s*bike", "assault\\s*bike", "air\\s*bike"),
    category: "cardio",
    dominantCapacity: "vo2max",
    secondaryCapacities: ["lactique", "endurance_force"],
    energetics: { atp_pcr: 0.05, glycolytic: 0.35, oxidative: 0.6 },
    typicalLoad: 0.2,
    secondsPerRep: 0.4, // calories
    isCardio: true,
  },
  {
    id: "bike_erg",
    name: "BikeErg",
    aliases: re("bike\\s*erg", "bikeerg"),
    category: "cardio",
    dominantCapacity: "vo2max",
    secondaryCapacities: ["endurance_force"],
    energetics: { atp_pcr: 0.03, glycolytic: 0.22, oxidative: 0.75 },
    typicalLoad: 0.15,
    secondsPerRep: 0.15,
    isCardio: true,
  },
  {
    id: "ski_erg",
    name: "SkiErg",
    aliases: re("ski\\s*erg", "skierg"),
    category: "cardio",
    dominantCapacity: "vo2max",
    secondaryCapacities: ["endurance_force", "lactique"],
    energetics: { atp_pcr: 0.05, glycolytic: 0.3, oxidative: 0.65 },
    typicalLoad: 0.25,
    secondsPerRep: 0.22,
    isCardio: true,
  },
  {
    id: "swim",
    name: "Natation",
    aliases: re("swim", "natation", "nage"),
    category: "cardio",
    dominantCapacity: "vo2max",
    secondaryCapacities: ["endurance_force", "skill"],
    energetics: { atp_pcr: 0.05, glycolytic: 0.25, oxidative: 0.7 },
    typicalLoad: 0.2,
    secondsPerRep: 1, // par m, brasse moyenne
    isCardio: true,
  },
  {
    id: "shuttle",
    name: "Shuttle Run",
    aliases: re("shuttle\\s*run"),
    category: "cardio",
    dominantCapacity: "lactique",
    secondaryCapacities: ["vo2max", "puissance"],
    energetics: { atp_pcr: 0.15, glycolytic: 0.55, oxidative: 0.3 },
    typicalLoad: 0.15,
    secondsPerRep: 0.3,
    isCardio: true,
  },

  // ─── HYROX SPECIFIQUE ─────────────────────────────────────────────────────
  {
    id: "sled_push",
    name: "Sled Push",
    aliases: re("sled\\s*push", "pouss[ée][e]?\\s*de\\s*tra[iî]neau"),
    category: "hyrox",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["force_max", "lactique", "gainage"],
    energetics: { atp_pcr: 0.15, glycolytic: 0.55, oxidative: 0.3 },
    typicalLoad: 0.6,
    secondsPerRep: 60, // par "set" / station
  },
  {
    id: "sled_pull",
    name: "Sled Pull",
    aliases: re("sled\\s*pull", "traction\\s*de\\s*tra[iî]neau"),
    category: "hyrox",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["force_max", "lactique", "gainage"],
    energetics: { atp_pcr: 0.15, glycolytic: 0.55, oxidative: 0.3 },
    typicalLoad: 0.55,
    secondsPerRep: 50,
  },
  {
    id: "burpee_broad",
    name: "Burpee Broad Jump",
    aliases: re("burpee\\s*broad\\s*jump"),
    category: "hyrox",
    dominantCapacity: "vo2max",
    secondaryCapacities: ["puissance", "endurance_force"],
    energetics: { atp_pcr: 0.15, glycolytic: 0.5, oxidative: 0.35 },
    typicalLoad: 0.35,
    secondsPerRep: 6,
  },
  {
    id: "farmer",
    name: "Farmers Carry",
    aliases: re("farmer'?s?\\s*carry", "port[ée]\\s*du\\s*fermier"),
    category: "hyrox",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["gainage", "force_max"],
    energetics: { atp_pcr: 0.1, glycolytic: 0.35, oxidative: 0.55 },
    typicalLoad: 0.5,
    secondsPerRep: 30,
  },
  {
    id: "sandbag_lunge",
    name: "Sandbag Lunges",
    aliases: re("sandbag\\s*lunge(s)?", "lunge\\s*sandbag"),
    category: "hyrox",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["gainage", "lactique"],
    energetics: { atp_pcr: 0.05, glycolytic: 0.45, oxidative: 0.5 },
    typicalLoad: 0.4,
    secondsPerRep: 3,
  },

  // ─── STRONGMAN ─────────────────────────────────────────────────────────────────────
  // Charges typiques très lourdes, dominante force maximale et endurance de force,
  // composante gainage essentielle. Filière ATP-PCr dominante avec basculement
  // glycolytique sur les enchainements (medley).
  {
    id: "atlas_stone",
    name: "Atlas Stone (to platform)",
    aliases: re(
      "atlas\\s*stone(s)?",
      "stone\\s*to\\s*shoulder",
      "stone\\s*lift",
      "stone\\s*over\\s*bar",
      "pierre\\s*d['’]?atlas",
      "chargement\\s*pierre"
    ),
    category: "weightlifting",
    dominantCapacity: "force_max",
    secondaryCapacities: ["endurance_force", "gainage", "puissance"],
    energetics: { atp_pcr: 0.7, glycolytic: 0.3, oxidative: 0 },
    typicalLoad: 0.85,
    secondsPerRep: 12,
  },
  {
    id: "yoke_walk",
    name: "Yoke Walk",
    aliases: re(
      "yoke\\s*walk",
      "yoke\\s*carry",
      "marche\\s*sous\\s*yoke",
      "port[ée]\\s*yoke"
    ),
    category: "weightlifting",
    dominantCapacity: "force_max",
    secondaryCapacities: ["gainage", "endurance_force"],
    energetics: { atp_pcr: 0.55, glycolytic: 0.35, oxidative: 0.1 },
    typicalLoad: 0.9,
    secondsPerRep: 25,
  },
  {
    id: "log_press",
    name: "Log Clean & Press",
    aliases: re(
      "log\\s*press",
      "log\\s*clean(\\s*(and|&|et)\\s*press)?",
      "log\\s*lift",
      "log\\s*overhead",
      "\u00e9paul[ée]-?jet[ée]?\\s*au\\s*log"
    ),
    category: "weightlifting",
    dominantCapacity: "force_max",
    secondaryCapacities: ["puissance", "skill", "gainage"],
    energetics: { atp_pcr: 0.8, glycolytic: 0.2, oxidative: 0 },
    typicalLoad: 0.8,
    secondsPerRep: 8,
  },
  {
    id: "farmer_handles_heavy",
    name: "Farmer's Handles (heavy)",
    aliases: re(
      "farmer'?s?\\s*handles?",
      "farmer'?s?\\s*walk",
      "heavy\\s*farmer'?s?",
      "port[ée]\\s*fermier\\s*lourd"
    ),
    category: "weightlifting",
    dominantCapacity: "force_max",
    secondaryCapacities: ["endurance_force", "gainage"],
    energetics: { atp_pcr: 0.55, glycolytic: 0.35, oxidative: 0.1 },
    typicalLoad: 0.85,
    secondsPerRep: 20,
  },
  {
    id: "tire_flip",
    name: "Tire Flip",
    aliases: re(
      "tire\\s*flip(s)?",
      "flip\\s*de\\s*pneu(s)?",
      "retournement\\s*de\\s*pneu(s)?",
      "truck\\s*tire\\s*flip"
    ),
    category: "weightlifting",
    dominantCapacity: "puissance",
    secondaryCapacities: ["force_max", "endurance_force", "gainage"],
    energetics: { atp_pcr: 0.6, glycolytic: 0.35, oxidative: 0.05 },
    typicalLoad: 0.8,
    secondsPerRep: 10,
  },
  {
    id: "sled_heavy",
    name: "Heavy Sled Drag",
    aliases: re(
      "heavy\\s*sled",
      "sled\\s*drag",
      "prowler\\s*push",
      "prowler\\s*sprint",
      "power\\s*sled",
      "tra[iî]neau\\s*lourd"
    ),
    category: "weightlifting",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["force_max", "lactique", "vo2max"],
    energetics: { atp_pcr: 0.3, glycolytic: 0.5, oxidative: 0.2 },
    typicalLoad: 0.8,
    secondsPerRep: 25,
  },
  {
    id: "axle_deadlift",
    name: "Axle Deadlift",
    aliases: re(
      "axle\\s*deadlift",
      "axle\\s*dl",
      "axle\\s*clean",
      "axle\\s*press",
      "barre\\s*axle",
      "fat\\s*bar\\s*deadlift"
    ),
    category: "weightlifting",
    dominantCapacity: "force_max",
    secondaryCapacities: ["endurance_force", "gainage", "skill"],
    energetics: { atp_pcr: 0.85, glycolytic: 0.15, oxidative: 0 },
    typicalLoad: 0.85,
    secondsPerRep: 6,
  },
  {
    id: "sandbag_carry",
    name: "Sandbag Carry / Over-Shoulder",
    aliases: re(
      "sandbag\\s*carry",
      "sandbag\\s*over\\s*shoulder",
      "sandbag\\s*to\\s*shoulder",
      "sandbag\\s*over\\s*bar",
      "sandbag\\s*clean",
      "sac\\s*de\\s*sable\\s*port[ée]",
      "port[ée]\\s*sac\\s*de\\s*sable"
    ),
    category: "weightlifting",
    dominantCapacity: "endurance_force",
    secondaryCapacities: ["force_max", "gainage", "puissance"],
    energetics: { atp_pcr: 0.4, glycolytic: 0.45, oxidative: 0.15 },
    typicalLoad: 0.7,
    secondsPerRep: 12,
  },
];

// Liste plate pour debug
export const MOVEMENT_COUNT = MOVEMENTS.length;
